krtomo/avatar-bi

- app/models/user.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20191126080319_devise_create_users.rb
- db/schema.rb
- test/fixtures/users.yml
- test/models/user_test.rb
deviseのインストール、usersテーブルのcreate
> install_devise_and_db:create

- Gemfile
- Gemfile.lock
- config/application.rb
- lib/odpt/odpt_seed.rb
- lib/odpt/railway_api.rb
- lib/odpt/station_api.rb
- lib/odpt/station_timetable_api.rb
- lib/odpt/train_api.rb
- lib/odpt/train_timetable_api.rb
公共交通オープンデータAPIを利用してデータを取得するメソッドを用意する
公共交通オープンデータAPIから、容易にデータを取り出してアプリ内で使用できるようにするため
- lib/　にclass作成し、autoloadするようにapplication.rbに記載
- Station, Railway, StationTimetable, RailwayTimetableを公共交通オープンデータから取り出せるclassメソッドを作成
- dbに流し込む初期データを作成するファイル(odpt_seed.rb)を作成
> Prepare odpt api methods

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/_flash.scss
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/application.scss
- app/views/devise/sessions/new.html.haml
- app/views/devise/shared/_links.html.haml
- app/views/layouts/_flash.html.haml
- app/views/layouts/application.html.haml
- config/application.rb
- config/locales/devise.ja.yml
devise周りの日本語化、およびdeviseからのエラーメッセージ・通知（flash）の表示
日本語ユーザを利用対象とするため。
また、エラー時の原因を明示するため。
> install_devise_ja_yml_and_g_flash

- db/migrate/20191126080319_devise_create_users.rb
- db/schema.rb
usersテーブルのthis_travel_timeとtotal_travel_timeの型をintに変更
> changed type from time into int

- app/assets/stylesheets/_contents.scss
- app/assets/stylesheets/_devise.scss
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/application.scss
- app/views/avatars/new.html.haml
- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/edit.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/layouts/application.html.haml
- app/views/users/index.html.haml
- app/views/users/show.html.haml
deviseによるログイン等のフォームSCSSの整形。
その他、全てのページに適応される部分（ヘッダなど）の位置調整。
ビューの視認性向上のため。
> Edit devise scss

- app/assets/javascripts/user.js
- app/controllers/users_controller.rb
「移動開始」「移動終了」ボタン押下で、現在時刻および座標を取得、移動中フラグの切り替えをUserテーブルに保存。
- start_time,end_timeの保存
- start_pos_lat,start_pos_long,end_pos_lat,end_pos_longの取得、保存
- is_movingの切り替え
アバターの移動計算、およびユーザの実績表示に用いるため。
> Edit start end btn w saving time

- app/assets/stylesheets/_show.scss
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/application.scss
- app/views/users/show.html.haml
ユーザ詳細ページのレイアウトと情報表示を実装。
ユーザのこれまでの成果を提示するため。
> Edit page showing user info

- app/controllers/users_controller.rb
- app/views/users/index.html.haml
- lib/travel.rb
> temp--track-avatar-travel

- app/assets/javascripts/travel.js
- app/controllers/users_controller.rb
- app/views/users/index.html.haml
- lib/travel.rb
アバターが電車を自由に乗り継いで行く機能を与えるメソッドを実装
アバターが現在地や自分の状況に合わせて移動する仮想旅行の機能を実現するため
アバターの移動に関わるメソッドはTravelクラスに実装
- 旅行開始時
アバターは現在駅から乗れる電車を検索し、時刻表を取得
- 旅行中
アバターは時刻表に従って移動
-  終点到着時
アバターは時刻表を破棄　次の移動は旅行開始時とおなじく時刻表を取得
> Add avatar travel function

- db/migrate/20191205040105_change_datatype_has_passed_of_passed_stations.rb
- db/schema.rb
passed_stations の has_passedの型をbooleanからintegerに変更
アバターが通過した回数を記録するため
> has_passed type changed

- app/assets/javascripts/map.js
- app/assets/javascripts/travel.js
- app/assets/javascripts/user.js
- app/assets/stylesheets/_contents.scss
- app/controllers/avatars_controller.rb
- app/controllers/stations_controller.rb
- app/controllers/users_controller.rb
- app/views/stations/station.json.jbuilder
- app/views/users/index.html.haml
- config/routes.rb
アバターがユーザ移動中に、現在駅から列車（時刻表）を選択し、それに合わせて現在位置を更新する関数を、数秒ごとに呼び出す機能を実装。
アバターの仮想旅行としての座標を更新するため。
> Set in60sec travel function

- app/assets/javascripts/map.js
- app/assets/javascripts/user.js
- app/assets/stylesheets/_avatars.scss
- app/assets/stylesheets/_contents.scss
- app/assets/stylesheets/_devise.scss
- app/assets/stylesheets/_show.scss
- app/controllers/avatars_controller.rb
- app/controllers/users_controller.rb
- app/views/avatars/new.html.haml
- app/views/layouts/_station_search.html.haml
- app/views/users/show.html.haml
- config/application.rb
- config/locales/models/ja.yml
コードレビュー時の指摘箇所をリファクタリング。
バリデーションエラーメッセージを日本語化。
> Refactoring scss and correcting 

- .gitignore
- 1_curr.csv
- app/assets/javascripts/map.js
- app/controllers/avatars_controller.rb
- db/csv/1_curr.csv
> Change map function

- app/controllers/avatars_controller.rb
- app/controllers/users_controller.rb
- app/views/users/show.html.haml
- lib/travel.rb
アバターの踏破路線や駅の記録機能及びユーザー詳細ページでの表示機能を実装した。
ユーザーが自分のアバターの移動の履歴の情報を得られるようにするため。
- travel.rb、Aavatars#travel の変更
getCurrentPosition関数の返り値を変更し、対応する箇所の記述を変更
1ループごとに、Passed_stationsテーブルへ新しく到達した駅を判定し追加
- Passed_railwayテーブルへの保存
user_controllerのshowアクション内において、路線の駅を全て踏破したかを判定し、していればpassed_railwayに追加
- ユーザー詳細ページの表示
show.html.hamlにおいて、passed_stations, passed_railwaysの情報表示
> 踏破駅、路線の記録と表示機能の追加

- app/controllers/users_controller.rb
- app/views/users/show.html.haml
踏破した路線別の駅数を、残り駅数でソートして表示
見やすくするため
> 踏破駅を残り駅数でソート

- app/assets/javascripts/avatar.js
- app/assets/javascripts/user.js
- app/controllers/avatars_controller.rb
- app/views/avatars/edit.html.haml
- app/views/avatars/new.html.haml
- app/views/users/index.html.haml
アバター作成画面での送信デフォルト値の設定と、アバターの編集画面の作成。
> Edit newavatar and create editavatar

- app/assets/javascripts/map.js
- app/controllers/avatars_controller.rb
- app/controllers/users_controller.rb
- app/views/users/show.html.haml
地図に情報を付加する
ユーザーが、現在の状態をより正確に把握し多くの情報を得られるようにするため。
- メイン画面マップ
ユーザーの現在地(精度円付き)を表示
アバターの現在地をユーザーの選んだアイコン画像で表示
アバターの軌跡を線で描画
- 履歴表示マップ
アバターの現在地を表示
踏破した駅をピンで表示、駅名と最近の通過日時表示
> Add information on map

- app/controllers/avatars_controller.rb
- app/controllers/users_controller.rb
アバター未作成時のリダイレクト、アバター作成時のcsv作成を実装
アバターを作成せずにログアウトしたユーザへの誘導、および初期ログイン時の地図読み込みエラーの対応のため。
- メイン画面遷移の際に、avatars[0]の有無を条件にリダイレクトを設定
- 作成したアバターの登録時に、home_stationの情報を格納したcsvファイルを作成
> 初期ログインのエラー修正

- app/assets/javascripts/map.js
履歴表示マップを改良
- 同じ座標に立てたピンをランダムで少しずらして表示
- 地図で路線以外の情報を落とす
> 地図に付加する情報の編集

- Gemfile
- Gemfile.lock
> update for upload to heroku

- app/assets/javascripts/style.js
- app/assets/stylesheets/_contents.scss
- app/assets/stylesheets/_flash.scss
- app/assets/stylesheets/_mixin.scss
- app/assets/stylesheets/_show.scss
- app/assets/stylesheets/_style.scss
- app/assets/stylesheets/_variables.scss
- app/views/devise/shared/_error_messages.html.haml
- app/views/layouts/_header.html.haml
- app/views/users/index.html.haml
- app/views/users/show.html.haml
> Edit show css

- app/assets/javascripts/map.js
- app/assets/javascripts/style.js
- app/assets/stylesheets/_contents.scss
- app/assets/stylesheets/_show.scss
- app/assets/stylesheets/_style.scss
- app/assets/stylesheets/_variables.scss
- app/controllers/application_controller.rb
- app/views/users/index.html.haml
- app/views/users/show.html.haml
レイアウト整形
・ユーザ詳細画面の踏破路線リストの表示・非表示をボタンで切り替え
・フォント修正
・ストリートビュー更新ボタンの挙動を実装
・ユーザ情報（名前とパスワード）の更新不可を修正
> ボタン編集、リスト整形、ユーザ情報更新

- app/controllers/users_controller.rb
- app/views/users/show.html.haml
ランキングから他ユーザの詳細ページへのアクセスを許可。
ログインユーザと詳細ページのユーザが一致しなければ、編集ボタンを非表示。
> ランキングからの他ユーザ詳細ページアクセス

- app/assets/javascripts/style.js
- app/assets/javascripts/user.js
- app/assets/stylesheets/_mixin.scss
- app/assets/stylesheets/_show.scss
- app/assets/stylesheets/_style.scss
- app/assets/stylesheets/_variables.scss
- app/controllers/users_controller.rb
- app/views/users/index.html.haml
- app/views/users/show.html.haml
モーダル画面のレイアウト整形、およびボタン押下時のアクションを追加
> モーダル画面整形、ボタンアクション編集

- app/assets/javascripts/travel.js
- app/controllers/avatars_controller.rb
- lib/travel.rb
> Decrease sqlquery

- app/assets/javascripts/travel.js
- app/controllers/avatars_controller.rb
- app/controllers/users_controller.rb
- lib/travel.rb
> Refactoring
